 lab adhoc setup
 lab ansible-deploy-cr setup
 lab ansible-devops-practice setup
 lab ansible-galaxy setup
 lab ansible-optimize-cr setup
 lab ansible-playbooks-cr setup
 lab ansible-roles-cr setup
 lab ansible-roles-lab setup
 lab ansible-tower-cr setup
 lab ansible-vagrant-lab setup
 lab ansible-vagrant-practice setup
 lab ansible-vault-lab setup
 lab basic setup
 lab configure-ansible-vault setup
 lab configure-async setup
 lab configure-delegation setup
 lab creating-roles setup
 lab deploy-dynamic setup
 lab deploy setup
 lab execute-ansible-vault setup
 lab install setup
 lab jinja2-implement setup
 lab jinja2-lab setup
 lab manage setup
 lab manage-variables-facts setup
 lab manage-variables-inclusions setup
 lab manage-variables-playbooks setup
 lab manage-variables setup
 lab optimize-ansible-lab setup
 lab patterns setup
 lab playbookinternet setup
 lab playbook setup
 lab task-control-failures setup
 lab task-control-flowcontrol setup
 lab task-control-handlers setup
 lab task-control setup
 lab task-control-tags setup
 lab tower-install setup
 lab tower-webui setup
 lab troubleshoot-lab setup
 lab troubleshoot-managedhosts setup
 lab troubleshoot-playbooks setup
